name: Static analysis

on:
  push:
  pull_request:

jobs:
  luacheck:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Setup luarocks
        run: sudo apt install -y luarocks

      - name: Setup dependencies
        run: make deps

      - run: echo $(luarocks path --lr-bin) >> $GITHUB_PATH

      - name: Run luacheck
        run: make luacheck

  emmylua_check:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-emmylua-analyzer

      - name: Run emmylua_check
        run: make emmylua_check
